# Generated by Django 6.0.1 on 2026-01-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='adres',
            field=models.CharField(default=1, max_length=255, verbose_name='адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='base',
            name='description',
            field=models.TextField(default=1, verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='base',
            name='logo',
            field=models.ImageField(default=1, upload_to='base/', verbose_name='Логотив'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='base',
            name='phone',
            field=models.CharField(default=1, max_length=255, verbose_name='номер'),
            preserve_default=False,
        ),
    ]
