# Generated by Django 6.0.1 on 2026-01-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(default=1, upload_to='base/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
