# Generated by Django 6.0.1 on 2026-01-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='описание')),
                ('phone', models.CharField(max_length=255, verbose_name='номер')),
                ('adres', models.CharField(max_length=255, verbose_name='адрес')),
                ('logo', models.ImageField(upload_to='base/', verbose_name='Логотив')),
            ],
            options={
                'verbose_name': 'данный',
                'verbose_name_plural': 'данные',
            },
        ),
    ]
