# Generated by Django 6.0.1 on 2026-01-17 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='logo',
        ),
    ]
